application.configuration.artifact:
  cache-location: ${user.home}/.module-graph/pom-cache
  repositories:
    - local: true
      path: ${user.home}/.m2/repository
    - local: false
      path: http://repo1.maven.org/maven2
---
spring:
  profiles.active: dev
---
spring:
  data:
    neo4j:
      uri: bolt://localhost
      username: neo4j
      password: admin

logging:
  level:
    root: info
    org.springframework.data.neo4j: debug

