application.configuration.artifact:
  pom-cache: ${user.home}/.pom-cache
  repositories:
    - isLocal: true
      path: ${user.home}/.m2/repository
    - isLocal: false
      path: http://repo1.maven.org/maven2
---
spring:
  profiles.active: dev
---
spring:
  data:
    neo4j:
      uri: bolt://localhost
      username: neo4j
      password: admin

logging:
  level:
    root: info
    org.springframework.data.neo4j: debug

